name: 🧪 run-dependency-checks

on:
  workflow_dispatch:
  schedule:
  - cron: "1 0 * * FRI"

jobs:
  run-dependency-checks-rust:
    name: run-dependency-checks
    runs-on: docker
    steps:
      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@stable

      - uses: actions/checkout@v6
        with:
          submodules: "true"

      - name: Install cargo-upgrades
        run: cargo install cargo-upgrades

      - name: Check if dependencies are up-to-date
        run: cargo upgrades
