//! A smoke run of the core of the `scaling` example (Phase 5 T10): a tiny problem, two
//! timed evaluations per path, on any number of ranks (CI's root job runs one; by hand
//! also two, under an external timeout and with the macOS loopback flags):
//!
//! ```sh
//! cargo test -p nd-fmm-validate --test scaling --no-run   # note the executable
//! RUST_MIN_STACK=8388608 timeout 300 mpirun --mca btl_tcp_if_include lo0 \
//!   --mca oob_tcp_if_include lo0 -n 2 target/debug/deps/scaling-<hash>
//! ```
//!
//! It checks the report's fields (every point passed and owned once, the stages of both
//! paths per rank, the traffic: none on one rank, sent equal to received over the ranks
//! on several), the overlapped path bit for bit the blocking one, the one-rank reference
//! (zero difference on one rank, within 100 u_T on several), the owners' input (no point
//! moves) and the errors against the direct sum: those of the one-rank run of the same
//! workload, which every rank repeats on its own communicator, within 0.1% in f64 and 1%
//! in f32 (docs/phase5/README.md, "Accuracy measures"). The workload is generated by
//! index: the same points for every N and every rank.
//!
//! It also checks the placement (Phase 5N T2): the nodes and ranks per node from
//! `split_shared` (one node here), every rank's host and CPUs, the MPI library and the new
//! report lines; the Slurm fields are checked on given variables, without Slurm.
//!
//! One test initialises MPI (at `Threading::Funneled`). Error measures: as named at each
//! check; the timings are only checked to be finite and non-negative.

use mpi::Threading;
use mpi::collective::SystemOperation;
use mpi::topology::SimpleCommunicator;
use mpi::traits::{Communicator, CommunicatorCollectives};
use nd_fmm_validate::fmm_accuracy::Distribution;
use nd_fmm_validate::scaling::{
    COMPUTE, Input, Overlap, Report, STAGES, Settings, SlurmJob, Workload, run,
};

/// The tiny problem: 1,500 points of the cube.
const WORKLOAD: Workload = Workload::new(Distribution::Cube, 1500);

/// p = 3, both paths, two timed evaluations, two charge vectors at 100 targets, and the
/// one-rank reference.
fn settings() -> Settings {
    Settings {
        overlap: Overlap::Both,
        evaluations: 2,
        vectors: 2,
        sampled: 100,
        reference: true,
        ..Settings::new(3)
    }
}

#[test]
fn smoke_run_of_the_scaling_core() {
    let (universe, provided) = mpi::initialize_with_threading(Threading::Funneled)
        .expect("this test owns MPI initialization");
    assert!(provided >= Threading::Funneled, "MPI provides {provided:?}");
    let comm = universe.world();
    the_workload_is_generated_by_index();
    let one = SimpleCommunicator::self_comm();
    for (precision, bound) in [("f64", 1e-3), ("f32", 1e-2)] {
        let (report, alone) = if precision == "f64" {
            (
                run::<f64>(&WORKLOAD, &settings(), &comm),
                run::<f64>(&WORKLOAD, &settings(), &one),
            )
        } else {
            (
                run::<f32>(&WORKLOAD, &settings(), &comm),
                run::<f32>(&WORKLOAD, &settings(), &one),
            )
        };
        check_fields(&report, &comm);
        check_fields(&alone, &one);
        // Error measure: the relative difference of each root-mean-square error from the
        // one-rank run's.
        let (e, a) = (report.errors.unwrap(), alone.errors.unwrap());
        for (name, got, want) in [
            ("φ L2", e.potential.l2, a.potential.l2),
            ("φ max", e.potential.max, a.potential.max),
            ("∇φ L2", e.gradient.l2, a.gradient.l2),
            ("∇φ max", e.gradient.max, a.gradient.max),
        ] {
            assert!(
                (got - want).abs() <= bound * want,
                "{precision}: {name} {got:e} on {} ranks, {want:e} on one",
                report.ranks
            );
        }
        // p = 3 on the cube: errors of the order of the single-translation prediction.
        assert!(e.potential.l2 > 0.0 && e.potential.l2 < 1e-2, "{e:?}");
        // Error measure: relative L2 and max differences, and the count of differing
        // values. One rank with the points in index order is its own reference; several
        // ranks reorder the points within a leaf, within 100 u_T.
        let unit = if precision == "f32" {
            2f64.powi(-24)
        } else {
            2f64.powi(-53)
        };
        for r in [&report, &alone] {
            let reference = r.reference.unwrap();
            if r.ranks == 1 {
                assert_eq!(reference.differing, 0, "{precision}: {reference:?}");
            }
            assert!(
                reference.potential_l2 <= 100.0 * unit && reference.gradient_l2 <= 100.0 * unit,
                "{precision} on {} ranks: {reference:?}",
                r.ranks
            );
        }
        if comm.rank() == 0 {
            println!("{report}");
        }
    }
    inputs_rank0_and_owners(&comm);
}

/// Every point and charge depends on its index and the seed only; the sample is distinct.
fn the_workload_is_generated_by_index() {
    let larger = Workload {
        n: 3000,
        ..WORKLOAD
    };
    for i in [0, 1, 777, 1499] {
        assert_eq!(WORKLOAD.point(i), larger.point(i));
        assert_eq!(WORKLOAD.charge(3, i), larger.charge(3, i));
        assert!(WORKLOAD.point(i).iter().all(|c| (-1.0..1.0).contains(c)));
    }
    assert_ne!(WORKLOAD.point(0), WORKLOAD.point(1));
    assert_ne!(WORKLOAD.charge(0, 5), WORKLOAD.charge(1, 5));
    let mut sample = WORKLOAD.sample(100);
    sample.sort_unstable();
    sample.dedup();
    assert_eq!(sample.len(), 100);
    assert!(sample.iter().all(|&i| i < WORKLOAD.n));
    let shares: Vec<usize> = (0..WORKLOAD.n).map(|i| WORKLOAD.share(i, 3)).collect();
    assert!(
        (0..3).all(|r| shares.contains(&r)),
        "every rank gets points"
    );
}

/// The fields of a report of [`settings`] on `comm`.
fn check_fields(report: &Report, comm: &SimpleCommunicator) {
    let size = comm.size() as usize;
    let n = WORKLOAD.n;
    assert_eq!(report.ranks, size);
    assert_eq!(report.rows.len(), size);
    assert_eq!(report.precision.len(), 3);
    assert_eq!(report.threading.threads, 1);
    let sum = |f: &dyn Fn(&nd_fmm_validate::scaling::RankRow) -> usize| -> usize {
        report.rows.iter().map(f).sum()
    };
    assert_eq!(sum(&|r| r.input), n, "every point passed once");
    assert_eq!(sum(&|r| r.sources), n, "every source owned once");
    assert_eq!(sum(&|r| r.targets), n, "every target owned once");
    assert!(
        sum(&|r| r.leaves) >= n / 64,
        "the leaves hold at most 64 points"
    );
    assert!(sum(&|r| r.lists.u) > 0 && sum(&|r| r.lists.v) > 0);
    for row in &report.rows {
        assert!(row.build.iter().all(|t| t.is_finite() && *t >= 0.0));
        assert!(row.held[0] > 0, "every rank holds local boxes");
        assert!(row.memory.total() > row.memory.coefficients);
        assert!(row.memory.coefficients > 0.0);
    }
    // The traffic: none on one rank; on several, every message and value sent is received.
    let t = |f: &dyn Fn(&nd_fmm_validate::scaling::RankTraffic) -> usize| -> usize {
        report.rows.iter().map(|r| f(&r.traffic)).sum()
    };
    if size == 1 {
        assert_eq!(t(&|t| t.sources.values_sent + t.multipoles.values_sent), 0);
        assert_eq!(t(&|t| t.coarse_received + t.blocks[1]), 0);
        assert!(report.rows[0].held[1] == 0, "no ghost on one rank");
    } else {
        assert_eq!(
            t(&|t| t.sources.messages_sent),
            t(&|t| t.sources.messages_received)
        );
        assert_eq!(
            t(&|t| t.sources.values_sent),
            t(&|t| t.sources.values_received)
        );
        assert_eq!(
            t(&|t| t.multipoles.values_sent),
            t(&|t| t.multipoles.values_received)
        );
        assert!(t(&|t| t.sources.values_sent) > 0);
        assert_eq!(t(&|t| t.charges[0]), t(&|t| t.charges[1]));
        assert_eq!(t(&|t| t.output[0]), t(&|t| t.output[1]));
    }
    // Both paths, a median per rank and stage; the coarse gather only in the overlapped.
    assert_eq!(report.paths.len(), 2);
    assert_eq!(
        report.differing,
        Some(0),
        "overlap is bit for bit the blocking path"
    );
    for path in &report.paths {
        assert_eq!(path.medians.len(), size);
        for m in &path.medians {
            for (k, t) in m.iter().enumerate() {
                if k == 7 && !path.overlapped {
                    assert!(t.is_nan(), "no gather time in the blocking path");
                } else {
                    assert!(t.is_finite() && *t >= 0.0, "{}: {t}", STAGES[k]);
                }
            }
            let compute: f64 = COMPUTE.iter().map(|&k| m[k]).sum();
            assert!(compute <= m[15], "the compute stages within the total");
        }
        assert!(path.wall >= path.reduced(15)[0] * 0.999);
        let [max, min, mean] = path.compute();
        assert!(min <= mean && mean <= max && max > 0.0);
    }
    // The placement: these tests run on one node.
    let placement = &report.placement;
    assert_eq!(placement.nodes, 1, "{placement:?}");
    assert_eq!(placement.ranks_per_node, vec![size]);
    assert_eq!(placement.node, vec![0; size]);
    assert_eq!(placement.hosts.len(), size);
    assert_eq!(placement.cpus.len(), size);
    assert!(
        placement
            .hosts
            .iter()
            .all(|h| !h.is_empty() && !h.contains('\n'))
    );
    assert!(placement.cpus.iter().all(|c| !c.is_empty()));
    assert!(!placement.mpi_library.is_empty() && !placement.mpi_library.contains('\n'));
    let summaries = report.summaries();
    assert_eq!(summaries.len(), 2);
    assert!(
        summaries
            .iter()
            .all(|s| s.contains(" nodes=1 ") && s.contains(&format!("ranks_per_node={size}")))
    );
    assert!(
        summaries[0].contains(&format!("ranks={size}")) && summaries[0].contains("overlap=off")
    );
    assert!(summaries[1].contains("overlap=on") && summaries[1].contains("phi_l2="));
    let text = report.to_string();
    assert!(
        text.contains("### Evaluation, blocking") && text.contains("### Evaluation, overlapped")
    );
    assert!(text.contains("C5.2 measure"));
    assert!(text.contains(&format!(
        "- placement: 1 node(s) ({}), ranks per node {size}",
        placement.hosts[0]
    )));
    assert!(text.contains("one node over shared memory"));
    assert!(text.contains("### Placement per rank"));
    assert_eq!(text.contains("- Slurm: job "), placement.slurm.is_some());
}

/// The Slurm job of given variables: none without `SLURM_JOB_ID`; the binding Slurm
/// reports with its list, or "not set" when the launcher binds. Needs no Slurm and no MPI.
#[test]
fn slurm_job_from_variables() {
    let vars = |pairs: &'static [(&'static str, &'static str)]| {
        move |name: &str| {
            pairs
                .iter()
                .find(|(k, _)| *k == name)
                .map(|(_, v)| v.to_string())
        }
    };
    assert_eq!(SlurmJob::from_variables(vars(&[])), None);
    assert_eq!(
        SlurmJob::from_variables(vars(&[("SLURM_JOB_ID", ""), ("SLURM_JOB_QOS", "test")])),
        None
    );
    let job = SlurmJob::from_variables(vars(&[
        ("SLURM_JOB_ID", "238836"),
        ("SLURM_JOB_QOS", "test"),
        ("SLURM_JOB_PARTITION", "kathleen"),
        ("SLURM_JOB_NODELIST", "node-c11b-[001-002]"),
    ]))
    .expect("a job");
    assert_eq!(job.id, "238836");
    assert_eq!(job.cpu_bind, None);
    assert_eq!(
        job.to_string(),
        "job 238836, QoS test, partition kathleen, nodes node-c11b-[001-002]; binding by \
         Slurm: not set (the launcher binds)"
    );
    let bound = SlurmJob::from_variables(vars(&[
        ("SLURM_JOB_ID", "1"),
        ("SLURM_CPU_BIND", "quiet,mask_cpu:0x1,0x100000"),
        ("SLURM_CPU_BIND_LIST", "0x1,0x100000"),
    ]))
    .expect("a job");
    assert_eq!(
        bound.cpu_bind.as_deref(),
        Some("quiet,mask_cpu:0x1,0x100000 (list 0x1,0x100000)")
    );
    assert!(
        bound
            .to_string()
            .contains("QoS unknown, partition unknown, nodes unknown")
    );
}

/// Every point on rank 0, and every point on its owner: the points as passed, and with the
/// owners' input no point moves.
fn inputs_rank0_and_owners(comm: &SimpleCommunicator) {
    let rank = comm.rank() as usize;
    for input in [Input::Rank0, Input::Owners] {
        let settings = Settings {
            input,
            evaluations: 1,
            ..Settings::new(3)
        };
        let report = run::<f64>(&WORKLOAD, &settings, comm);
        let row = &report.rows[rank];
        match input {
            Input::Rank0 => {
                assert_eq!(row.input, if rank == 0 { WORKLOAD.n } else { 0 });
            }
            _ => {
                assert_eq!(
                    (row.sources, row.targets),
                    (row.input, row.input),
                    "rank {rank}: the owners' input moves no point"
                );
                let moved = usize::from(row.traffic.charges[0] != row.traffic.charges[1]);
                let mut any = 0usize;
                comm.all_reduce_into(&moved, &mut any, SystemOperation::sum());
                assert_eq!(any, 0);
            }
        }
    }
}
