//! Strong and weak scaling of the distributed host FMM (Phase 5 T10, C5.3): the core of
//! the `scaling` example.
//!
//! One [`run`] builds one `nd_fmm_exec::fmm::Fmm` on every rank of a communicator,
//! evaluates it repeatedly and reports, per rank and reduced over the ranks
//! ([`Report`]):
//! - the work as built: input points, owned sources and targets, leaves, list pairs, held
//!   boxes (local, ghost, `Global`);
//! - the build by part (`BuildTimings`: domain, octree, plan, redistribution, tables,
//!   evaluator with its exchange builds, load), the median over [`Settings::builds`];
//! - the evaluation by stage ([`STAGES`]): the median per rank over
//!   [`Settings::evaluations`] after one warm-up, then the maximum, minimum and mean over
//!   the ranks and the load imbalance (maximum over mean) of the compute stages;
//! - per exchange the messages and bytes per rank ([`RankTraffic`]);
//! - memory per rank: the formula of docs/design/distributed-fmm.md §9.2 evaluated
//!   ([`MemoryModel`], a *model*), and the resident size where the machine reports it
//!   without a new dependency ([`resident_memory`]);
//! - optionally the errors against the direct sum at sampled targets ([`Errors`]) and the
//!   difference from the one-rank `Fmm` over every point in index order ([`Reference`]);
//! - where the ranks ran ([`Placement`], Phase 5N T2): the nodes and the ranks per node
//!   (from `split_shared`), each rank's host and CPUs, the MPI library, and on a cluster
//!   the Slurm job with its QoS, node list and binding ([`SlurmJob`]).
//!
//! Nothing here asserts a timing; the smoke test checks the fields and the errors.
//!
//! # The workload
//!
//! A [`Workload`] generates **every point by its index** (docs/design/distributed-fmm.md
//! §14.4, S7): point i is drawn from its own generator, seeded by a hash of the seed and
//! i, so a rank produces its own points without drawing the others', and the problem of
//! N points is the first N points of every larger one (the weak-scaling problems are
//! nested). The charges of vector k are drawn the same way from `seed + 1 + k`. The
//! distributions are those of [`fmm_accuracy`](crate::fmm_accuracy) (design §8.2), drawn
//! point by point; the Gaussian clusters take point i in cluster i mod 5. The tree is the
//! adaptive one of the C3.3 problems: `max_level` 16 and 64 points per leaf.
//!
//! # Input distributions
//!
//! [`Input`]: every point on rank 0; a seeded random share (point i on rank
//! `hash(i) mod P`); or every point already on the rank that owns its leaf, found by a
//! first build from the share (the partition does not depend on the input, Phase 5 T4).
//! In every case the output is that of the one-rank `Fmm` over the union of the inputs in
//! rank order, bit for bit, and within 100 u_T of the one-rank `Fmm` over the points in
//! index order (docs/design/distributed-fmm.md §5), which [`Reference`] measures.
//!
//! # Errors against the direct sum
//!
//! As in [`fmm_accuracy`](crate::fmm_accuracy): the root mean squares over the charge
//! vectors of the relative L2 and max errors of φ and ∇φ at the sampled targets, against
//! `direct_sum` in f64 over every source with the charges rounded to the FMM's precision,
//! divided by 4π. The direct sum is computed once over the ranks, each rank over the
//! sources it passed, and summed (an all-reduce), so it changes with the rank count only
//! in the last bits.

use std::collections::{BTreeSet, HashMap};
use std::fmt;
use std::time::{Duration, Instant};

use mpi::collective::SystemOperation;
use mpi::datatype::PartitionMut;
use mpi::topology::SimpleCommunicator;
use mpi::traits::{Communicator, CommunicatorCollectives, Equivalence, Root};
use nd_fmm_exec::fmm::{BuildTimings, Fmm, FmmBuilder, ListSizes, Output, StageTimings, Traffic};
use nd_fmm_exec::geometry::{contains, integer_centre};
use nd_fmm_exec::operator::SimdScalar;
use nd_fmm_exec::tables::M2lStrategy;
use nd_fmm_exec::threading::ThreadingReport;
use nd_fmm_math::RealScalar;
use nd_fmm_ref::p2p::direct_sum;
use nd_fmm_tables::cache::Stored;

use crate::bench::{cores, cpu_model, target, toolchain};
use crate::fmm_accuracy::{CLUSTER_CENTRES, CLUSTER_WIDTH, Distribution, PLUMMER_SCALE};
use crate::metrics::{ErrorAccumulator, ErrorNorms};
use crate::{SplitMix64, points};

/// The deepest level of a leaf: that of the C3.3 problems.
pub const MAX_LEVEL: usize = 16;

/// The refinement target: 64 points per leaf, the host path's default.
pub const MAX_POINTS_PER_LEAF: usize = 64;

/// Values per target in the output: φ and ∇φ.
const OUTPUT_VALUES: usize = 4;

/// A problem whose points and charges are generated by index (module documentation).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Workload {
    /// The point distribution.
    pub distribution: Distribution,
    /// The number of points, sources equal to targets.
    pub n: usize,
    /// The seed of the points, the share and the sample; charge vector k uses
    /// `seed + 1 + k`.
    pub seed: u64,
}

/// The seed of the workloads of the `scaling` example.
pub const SEED: u64 = 0x5ca1e;

/// What [`hash`] mixes into the seed for the random share and for the sample, so that
/// neither correlates with the points.
const SHARE_SALT: u64 = 0x5_4a7e;
const SAMPLE_SALT: u64 = 0x5_a3b1e;

/// A hash of `seed` and `i`: SplitMix64's output on the mixed seed XOR i, so that
/// successive indices give unrelated generators.
pub fn hash(seed: u64, i: u64) -> u64 {
    let mixed = SplitMix64::new(seed).next_u64();
    SplitMix64::new(mixed ^ i).next_u64()
}

impl Workload {
    /// N points of `distribution` from [`SEED`].
    pub const fn new(distribution: Distribution, n: usize) -> Self {
        Self {
            distribution,
            n,
            seed: SEED,
        }
    }

    /// Point `i`, drawn from its own generator (module documentation).
    pub fn point(&self, i: usize) -> [f64; 3] {
        let mut rng = SplitMix64::new(hash(self.seed, i as u64));
        let origin = [0.0; 3];
        let drawn = match self.distribution {
            Distribution::Cube => points::cube(&mut rng, 1, origin, 1.0),
            Distribution::Sphere => points::sphere(&mut rng, 1, origin, 1.0),
            Distribution::Plummer => points::plummer(&mut rng, 1, origin, PLUMMER_SCALE),
            Distribution::Clusters => points::gaussian_clusters(
                &mut rng,
                1,
                &CLUSTER_CENTRES[i % CLUSTER_CENTRES.len()..][..1],
                CLUSTER_WIDTH,
            ),
        };
        drawn[0]
    }

    /// The charge of point `i` in charge vector `vector`, uniform in [−1, 1).
    pub fn charge(&self, vector: usize, i: usize) -> f64 {
        let seed = self.seed.wrapping_add(1 + vector as u64);
        points::charges(&mut SplitMix64::new(hash(seed, i as u64)), 1)[0]
    }

    /// The rank of `size` that point `i` goes to in the random share.
    pub fn share(&self, i: usize, size: usize) -> usize {
        (hash(self.seed ^ SHARE_SALT, i as u64) % size.max(1) as u64) as usize
    }

    /// `count` distinct indices of targets, seeded, in the order drawn.
    ///
    /// # Panics
    ///
    /// If `count > n`.
    pub fn sample(&self, count: usize) -> Vec<usize> {
        assert!(count <= self.n, "more samples than points");
        let mut rng = SplitMix64::new(hash(self.seed ^ SAMPLE_SALT, 0));
        let mut seen = BTreeSet::new();
        let mut sample = Vec::with_capacity(count);
        while sample.len() < count {
            let i = (((rng.next_u64() >> 32) * self.n as u64) >> 32) as usize;
            if seen.insert(i) {
                sample.push(i);
            }
        }
        sample
    }
}

/// Where the points are when `build` is called (docs/phase5/README.md, "Workloads").
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Input {
    /// Every point on rank 0.
    Rank0,
    /// Point i on rank `hash(i) mod P` ([`Workload::share`]).
    Share,
    /// Every point on the rank that owns its leaf.
    Owners,
}

impl Input {
    /// Every input distribution.
    pub const ALL: [Self; 3] = [Self::Rank0, Self::Share, Self::Owners];

    /// The name: "rank0", "share" or "owners".
    pub fn name(self) -> &'static str {
        match self {
            Self::Rank0 => "rank0",
            Self::Share => "share",
            Self::Owners => "owners",
        }
    }

    /// The input of a [`name`](Self::name), if there is one.
    pub fn from_name(name: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|i| i.name() == name)
    }

    /// A description, for reports.
    pub fn description(self) -> &'static str {
        match self {
            Self::Rank0 => "every point on rank 0",
            Self::Share => "a seeded random share (point i on rank hash(i) mod P)",
            Self::Owners => "every point on the rank that owns its leaf",
        }
    }
}

/// Which evaluation paths a [`run`] times.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Overlap {
    /// Blocking exchanges only.
    Off,
    /// Overlapped exchanges only (`FmmBuilder::overlap`, Phase 5 T9).
    On,
    /// Both on one build, the evaluations alternating (`Fmm::set_overlap`), a block each.
    Both,
}

impl Overlap {
    /// The name: "off", "on" or "both".
    pub fn name(self) -> &'static str {
        match self {
            Self::Off => "off",
            Self::On => "on",
            Self::Both => "both",
        }
    }

    /// The overlap of a [`name`](Self::name), if there is one.
    pub fn from_name(name: &str) -> Option<Self> {
        [Self::Off, Self::On, Self::Both]
            .into_iter()
            .find(|o| o.name() == name)
    }

    /// The paths, blocking first.
    fn paths(self) -> &'static [bool] {
        match self {
            Self::Off => &[false],
            Self::On => &[true],
            Self::Both => &[false, true],
        }
    }
}

/// How a [`run`] builds, evaluates and checks.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Settings {
    /// The degree; gradients are always on.
    pub p: usize,
    /// Rayon threads per rank (`FmmBuilder::threads`).
    pub threads: usize,
    /// The M2L strategy (`FmmBuilder::strategy`; the default `Auto`).
    pub strategy: M2lStrategy,
    /// The evaluation paths.
    pub overlap: Overlap,
    /// Where the points are passed in.
    pub input: Input,
    /// Builds; the build times are the median over them, and the last is evaluated.
    pub builds: usize,
    /// Timed evaluations per path, after one warm-up each.
    pub evaluations: usize,
    /// Charge vectors of the errors against the direct sum; none if 0.
    pub vectors: usize,
    /// Sampled targets of the errors.
    pub sampled: usize,
    /// Whether to compare with the one-rank `Fmm` over every point in index order, built
    /// on rank 0 alone ([`Reference`]).
    pub reference: bool,
}

impl Settings {
    /// Degree `p` on one thread, the default strategy, overlap off, the random share, one
    /// build, ten evaluations, no checks.
    pub const fn new(p: usize) -> Self {
        Self {
            p,
            threads: 1,
            strategy: M2lStrategy::Auto,
            overlap: Overlap::Off,
            input: Input::Share,
            builds: 1,
            evaluations: 10,
            vectors: 0,
            sampled: 1000,
            reference: false,
        }
    }
}

/// The stages of an evaluation as a [`run`] reports them, from `StageTimings`; times in
/// seconds, per rank the median over the evaluations.
///
/// The exchanges have three rows each: the stage of `StageTimings` (in the overlapped
/// path the rest of the overlapped stage outside the level calls), the exchange from post
/// to completion, and its exposed wait. In the blocking path the last two are the
/// stage itself: a blocking exchange is all exposed. "upward global" is the coarse gather
/// and the global M2M; the gather alone is timed only in the overlapped path
/// (`OverlapTimes::coarse_gather`), and is NaN (printed "–") in the blocking one.
pub const STAGES: [&str; 16] = [
    "forward charges",
    "load",
    "source exchange (stage)",
    "sources: post to completion",
    "sources: exposed wait",
    "upward local",
    "upward global (gather + global M2M)",
    "coarse gather",
    "multipole exchange (stage)",
    "multipoles: post to completion",
    "multipoles: exposed wait",
    "downward",
    "leaves",
    "output",
    "backward output",
    "total",
];

/// The positions in [`STAGES`] of the compute stages, whose imbalance a [`Report`] gives:
/// upward local, downward and leaves.
pub const COMPUTE: [usize; 3] = [5, 11, 12];

/// The positions in [`STAGES`] of the exposed waits and of the blocking exchange stages.
const EXPOSED: [usize; 2] = [4, 10];
const EXCHANGES: [usize; 2] = [2, 8];

/// The parts of the build as a [`run`] reports them, from `BuildTimings`, then the sum
/// and the wall time of `build` on the rank; seconds.
pub const BUILD_PARTS: [&str; 9] = [
    "domain",
    "octree",
    "plan",
    "redistribution",
    "tables",
    "evaluator",
    "load",
    "sum",
    "wall",
];

/// The values of [`STAGES`] for one evaluation of the path `overlapped`.
fn stage_values(t: &StageTimings, overlapped: bool) -> [f64; 16] {
    let s = Duration::as_secs_f64;
    let o = t.overlap.unwrap_or_default();
    let (sources, multipoles, gather) = if overlapped {
        (
            [s(&o.sources.total), s(&o.sources.exposed)],
            [s(&o.multipoles.total), s(&o.multipoles.exposed)],
            s(&o.coarse_gather),
        )
    } else {
        (
            [s(&t.exchange_sources); 2],
            [s(&t.exchange_multipoles); 2],
            f64::NAN,
        )
    };
    [
        s(&t.forward_charges),
        s(&t.load),
        s(&t.exchange_sources),
        sources[0],
        sources[1],
        s(&t.upward_local),
        s(&t.upward_global),
        gather,
        s(&t.exchange_multipoles),
        multipoles[0],
        multipoles[1],
        s(&t.downward),
        s(&t.evaluate_leaves),
        s(&t.output),
        s(&t.backward_output),
        s(&t.total()),
    ]
}

/// The values of [`BUILD_PARTS`] for one build.
fn build_values(t: &BuildTimings, wall: Duration) -> [f64; 9] {
    let s = Duration::as_secs_f64;
    [
        s(&t.domain),
        s(&t.octree),
        s(&t.plan),
        s(&t.redistribute),
        s(&t.tables),
        s(&t.evaluator),
        s(&t.load),
        s(&t.total()),
        s(&wall),
    ]
}

/// The median of `values` (the mean of the two middle ones for an even count); NaN if
/// empty or if the middle values are NaN.
pub fn median(mut values: Vec<f64>) -> f64 {
    if values.is_empty() {
        return f64::NAN;
    }
    values.sort_by(f64::total_cmp);
    let n = values.len();
    if n % 2 == 1 {
        values[n / 2]
    } else {
        0.5 * (values[n / 2 - 1] + values[n / 2])
    }
}

/// What a rank's exchanges move per evaluation, in messages and values (a value is the
/// precision's size in bytes): `Fmm::exchange_traffic` and `Fmm::exchange_sizes`, and the
/// moves of the charges and the output.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct RankTraffic {
    /// The source exchange.
    pub sources: Traffic,
    /// The multipole exchange, summed over the levels.
    pub multipoles: Traffic,
    /// The values of this rank's coarse blocks, which the coarse gather sends to each
    /// other rank.
    pub coarse_sent: usize,
    /// The values of the other ranks' coarse blocks, which it receives.
    pub coarse_received: usize,
    /// This rank's coarse blocks and the other ranks' (B_o, B_r).
    pub blocks: [usize; 2],
    /// The forward of the charges (an all-to-all-v): values sent (one per input source)
    /// and received (one per owned source).
    pub charges: [usize; 2],
    /// The backward of the output (an all-to-all-v): values sent (four per owned target)
    /// and received (four per input target).
    pub output: [usize; 2],
}

/// The memory of one rank by the formula of docs/design/distributed-fmm.md §9.2, in
/// bytes: a *model*, not a measurement.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct MemoryModel {
    /// Multipoles and locals: 2 n_c s K, a slot for every held box.
    pub coefficients: f64,
    /// Source store, target input and output: (4 (N_s + G_s) + 3 N_t + 4 N_t) s.
    pub points: f64,
    /// Box index and leaf numbering: 32 K + 13 (J_loc + J_gh).
    pub index: f64,
    /// The views: 12 E_V + 4 (E_near + E_W + E_X).
    pub views: f64,
    /// The two redistributions: 4 per sent and 12 per received point each.
    pub redistribution: f64,
    /// The exchange buffers: every value sent and received, the coarse gather's included.
    pub buffers: f64,
    /// The coarse exchange's keys and blocks: 16 B.
    pub coarse: f64,
    /// The partition bounds: 8 P.
    pub partition: f64,
}

impl MemoryModel {
    /// The sum of the parts.
    pub fn total(&self) -> f64 {
        self.coefficients
            + self.points
            + self.index
            + self.views
            + self.redistribution
            + self.buffers
            + self.coarse
            + self.partition
    }

    fn to_array(self) -> [f64; 8] {
        [
            self.coefficients,
            self.points,
            self.index,
            self.views,
            self.redistribution,
            self.buffers,
            self.coarse,
            self.partition,
        ]
    }

    fn from_array(a: &[f64]) -> Self {
        Self {
            coefficients: a[0],
            points: a[1],
            index: a[2],
            views: a[3],
            redistribution: a[4],
            buffers: a[5],
            coarse: a[6],
            partition: a[7],
        }
    }
}

/// One rank's work as built, its build times, its traffic and its memory.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct RankRow {
    /// The points this rank passed (sources, equal to the targets).
    pub input: usize,
    /// The sources this rank owns after the redistribution.
    pub sources: usize,
    /// The targets this rank owns.
    pub targets: usize,
    /// The local leaves.
    pub leaves: usize,
    /// The local leaves that hold no source.
    pub empty_leaves: usize,
    /// The interaction lists on this rank.
    pub lists: ListSizes,
    /// The held boxes: local, ghost and `Global`, as the octree classifies them.
    pub held: [usize; 3],
    /// The ghost source points the source exchange receives (G_s).
    pub ghost_sources: usize,
    /// [`BUILD_PARTS`], the median over the builds.
    pub build: [f64; 9],
    /// The traffic per evaluation.
    pub traffic: RankTraffic,
    /// The §9.2 formula, evaluated.
    pub memory: MemoryModel,
    /// The resident size at the end of the run, in bytes, where it can be read
    /// ([`resident_memory`]).
    pub resident: Option<f64>,
}

/// The position in [`RankRow::encode`] of the ghost held boxes, after the counts, the
/// build, the traffic, the memory and the resident size; the `Global` ones follow.
const ROW_VALUES: usize = 11 + 9 + 16 + 8 + 1;

impl RankRow {
    /// The row as values, for an all-gather (every count is exact in f64).
    fn encode(&self) -> Vec<f64> {
        let t = &self.traffic;
        let counts = [
            self.input,
            self.sources,
            self.targets,
            self.leaves,
            self.empty_leaves,
            self.lists.u,
            self.lists.v,
            self.lists.w,
            self.lists.x,
            self.ghost_sources,
            self.held[0],
        ];
        let traffic = [
            t.sources.messages_sent,
            t.sources.messages_received,
            t.sources.values_sent,
            t.sources.values_received,
            t.multipoles.messages_sent,
            t.multipoles.messages_received,
            t.multipoles.values_sent,
            t.multipoles.values_received,
            t.coarse_sent,
            t.coarse_received,
            t.blocks[0],
            t.blocks[1],
            t.charges[0],
            t.charges[1],
            t.output[0],
            t.output[1],
        ];
        let mut values: Vec<f64> = counts.iter().map(|&c| c as f64).collect();
        values.extend(self.build);
        values.extend(traffic.iter().map(|&c| c as f64));
        values.extend(self.memory.to_array());
        values.push(self.resident.unwrap_or(-1.0));
        values.push(self.held[1] as f64);
        values.push(self.held[2] as f64);
        values
    }

    /// The row of [`encode`](Self::encode).
    fn decode(v: &[f64]) -> Self {
        let c = |k: usize| v[k] as usize;
        let t = |k: usize| v[20 + k] as usize;
        Self {
            input: c(0),
            sources: c(1),
            targets: c(2),
            leaves: c(3),
            empty_leaves: c(4),
            lists: ListSizes {
                u: c(5),
                v: c(6),
                w: c(7),
                x: c(8),
            },
            ghost_sources: c(9),
            held: [c(10), c(ROW_VALUES), c(ROW_VALUES + 1)],
            build: core::array::from_fn(|k| v[11 + k]),
            traffic: RankTraffic {
                sources: Traffic {
                    messages_sent: t(0),
                    messages_received: t(1),
                    values_sent: t(2),
                    values_received: t(3),
                },
                multipoles: Traffic {
                    messages_sent: t(4),
                    messages_received: t(5),
                    values_sent: t(6),
                    values_received: t(7),
                },
                coarse_sent: t(8),
                coarse_received: t(9),
                blocks: [t(10), t(11)],
                charges: [t(12), t(13)],
                output: [t(14), t(15)],
            },
            memory: MemoryModel::from_array(&v[36..44]),
            resident: (v[44] >= 0.0).then_some(v[44]),
        }
    }
}

/// The stage times of one evaluation path.
#[derive(Clone, Debug, PartialEq)]
pub struct PathTimes {
    /// Whether the exchanges overlapped.
    pub overlapped: bool,
    /// Per rank, the median of each of [`STAGES`] over the evaluations.
    pub medians: Vec<[f64; 16]>,
    /// The median over the evaluations of the maximum over the ranks of the total: the
    /// evaluation's wall time.
    pub wall: f64,
}

impl PathTimes {
    /// The maximum, minimum and mean over the ranks of stage `k`.
    pub fn reduced(&self, k: usize) -> [f64; 3] {
        reduce_over(self.medians.iter().map(|m| m[k]))
    }

    /// The maximum, minimum and mean over the ranks of the sum of the [`COMPUTE`] stages.
    pub fn compute(&self) -> [f64; 3] {
        reduce_over(
            self.medians
                .iter()
                .map(|m| COMPUTE.iter().map(|&k| m[k]).sum()),
        )
    }

    /// The maximum over the ranks of the exposed waits of both exchanges together, and
    /// of the two exchange stages together: in an overlapped path against a blocking
    /// one, the C5.2 measure (docs/design/distributed-fmm.md §8.6).
    pub fn exchanges(&self) -> (f64, f64) {
        let max = |ks: [usize; 2]| {
            self.medians
                .iter()
                .map(|m| m[ks[0]] + m[ks[1]])
                .fold(0.0, f64::max)
        };
        (max(EXPOSED), max(EXCHANGES))
    }
}

/// The maximum, minimum and mean of `values`, NaN ignored (all NaN if every value is).
fn reduce_over(values: impl Iterator<Item = f64>) -> [f64; 3] {
    let values: Vec<f64> = values.filter(|v| !v.is_nan()).collect();
    if values.is_empty() {
        return [f64::NAN; 3];
    }
    [
        values.iter().copied().fold(f64::NEG_INFINITY, f64::max),
        values.iter().copied().fold(f64::INFINITY, f64::min),
        values.iter().sum::<f64>() / values.len() as f64,
    ]
}

/// The errors against the direct sum (module documentation).
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Errors {
    /// The charge vectors.
    pub vectors: usize,
    /// The sampled targets.
    pub sampled: usize,
    /// Root mean squares over the vectors of the relative L2 and max errors of φ.
    pub potential: ErrorNorms,
    /// The same of ∇φ.
    pub gradient: ErrorNorms,
}

/// The output of charge vector 0 against the one-rank `Fmm` of the same settings over
/// every point in index order, built and evaluated on rank 0 alone, over every target:
/// within 100 u_T on any rank count (docs/design/distributed-fmm.md §5), zero on one rank
/// with the points in index order.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Reference {
    /// Relative L2 difference of φ.
    pub potential_l2: f64,
    /// Relative L2 difference of ∇φ (the Euclidean norm per target).
    pub gradient_l2: f64,
    /// The largest difference of a value over the largest magnitude of a value, over φ
    /// and the gradient components.
    pub max_relative: f64,
    /// Values that differ in any bit.
    pub differing: usize,
}

/// The result of one [`run`], the same on every rank apart from
/// [`machine`](Self::machine), which rank 0 fills.
#[derive(Clone, Debug, PartialEq)]
pub struct Report {
    /// The machine: CPU, cores, host name, target and toolchain; on rank 0 only.
    pub machine: String,
    /// The problem.
    pub workload: Workload,
    /// The settings.
    pub settings: Settings,
    /// "f32" or "f64".
    pub precision: &'static str,
    /// The resolved M2L strategy.
    pub strategy: M2lStrategy,
    /// The number of ranks.
    pub ranks: usize,
    /// Rank 0's threading report: rayon threads, the MPI level and the BLAS variables.
    pub threading: ThreadingReport,
    /// The number of levels.
    pub nlevels: usize,
    /// Every rank's row, in rank order.
    pub rows: Vec<RankRow>,
    /// Each path's stage times, blocking first.
    pub paths: Vec<PathTimes>,
    /// With [`Overlap::Both`], the values of the two paths that differ in any bit, over
    /// every rank and evaluation (0: overlap is bit for bit the blocking path).
    pub differing: Option<usize>,
    /// The errors, if [`Settings::vectors`] > 0.
    pub errors: Option<Errors>,
    /// The reference check, if [`Settings::reference`].
    pub reference: Option<Reference>,
    /// How [`RankRow::resident`] was read.
    pub resident_kind: &'static str,
    /// Where the ranks ran: nodes, ranks per node, hosts and CPUs, the MPI library and
    /// the Slurm job (Phase 5N T2).
    pub placement: Placement,
}

/// The resident size of this process in bytes and how it was read: the peak (`VmHWM`) from
/// `/proc/self/status` on Linux; elsewhere the current resident size from `ps -o rss=`
/// (macOS reports no peak without a new dependency). `None` if neither can be read (for
/// example `ps` inside the macOS sandbox).
pub fn resident_memory() -> Option<(f64, &'static str)> {
    if let Ok(status) = std::fs::read_to_string("/proc/self/status") {
        let kib = status
            .lines()
            .find(|l| l.starts_with("VmHWM:"))
            .and_then(|l| l.split_whitespace().nth(1))
            .and_then(|v| v.parse::<f64>().ok())?;
        return Some((kib * 1024.0, "peak resident (VmHWM, /proc/self/status)"));
    }
    let out = std::process::Command::new("ps")
        .args(["-o", "rss=", "-p", &std::process::id().to_string()])
        .output()
        .ok()?;
    let kib: f64 = String::from_utf8(out.stdout).ok()?.trim().parse().ok()?;
    Some((
        kib * 1024.0,
        "resident at the end of the run (ps -o rss), not the peak",
    ))
}

/// The machine line of a report: CPU model, cores, host name, target and toolchain.
pub fn machine() -> String {
    let host = std::process::Command::new("hostname")
        .output()
        .ok()
        .filter(|o| o.status.success())
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map_or_else(|| "unknown".to_string(), |s| s.trim().to_string());
    format!(
        "{} ({}), host {host}, {}, {}",
        cpu_model(),
        cores(),
        target(),
        toolchain()
    )
}

/// The Slurm job a run is part of, from the environment of rank 0 (Phase 5N T2): what a
/// report on a cluster names beside its figures.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct SlurmJob {
    /// `SLURM_JOB_ID`.
    pub id: String,
    /// `SLURM_JOB_QOS`, if set.
    pub qos: Option<String>,
    /// `SLURM_JOB_PARTITION`, if set.
    pub partition: Option<String>,
    /// `SLURM_JOB_NODELIST`, if set.
    pub nodelist: Option<String>,
    /// The binding as Slurm reports it: `SLURM_CPU_BIND` (set inside an `srun` step with
    /// `--cpu-bind`), with `SLURM_CPU_BIND_LIST` if set; `None` when Slurm did not bind
    /// (for example `mpirun` inside the allocation, which binds itself).
    pub cpu_bind: Option<String>,
}

impl SlurmJob {
    /// The job of the variables that `var` returns, if `SLURM_JOB_ID` is among them.
    /// [`from_env`](Self::from_env) reads the process's environment; tests pass their own.
    pub fn from_variables(var: impl Fn(&str) -> Option<String>) -> Option<Self> {
        let id = var("SLURM_JOB_ID").filter(|id| !id.is_empty())?;
        let cpu_bind = var("SLURM_CPU_BIND").map(|bind| match var("SLURM_CPU_BIND_LIST") {
            Some(list) => format!("{bind} (list {list})"),
            None => bind,
        });
        Some(Self {
            id,
            qos: var("SLURM_JOB_QOS"),
            partition: var("SLURM_JOB_PARTITION"),
            nodelist: var("SLURM_JOB_NODELIST"),
            cpu_bind,
        })
    }

    /// The job of this process's environment, if it runs under Slurm.
    pub fn from_env() -> Option<Self> {
        Self::from_variables(|name| std::env::var(name).ok())
    }
}

impl fmt::Display for SlurmJob {
    /// For example `job 238836, QoS test, partition kathleen, nodes node-a[01-02];
    /// binding by Slurm: not set (the launcher binds)`.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let or = |v: &Option<String>| v.clone().unwrap_or_else(|| "unknown".to_string());
        write!(
            f,
            "job {}, QoS {}, partition {}, nodes {}; binding by Slurm: {}",
            self.id,
            or(&self.qos),
            or(&self.partition),
            or(&self.nodelist),
            self.cpu_bind
                .clone()
                .unwrap_or_else(|| "not set (the launcher binds)".to_string())
        )
    }
}

/// Where the ranks of a run ran (Phase 5N T2): the nodes, from one `split_shared` of the
/// communicator, each rank's host and CPUs, the MPI library and the Slurm job.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Placement {
    /// The shared-memory domains (nodes) of the communicator.
    pub nodes: usize,
    /// The ranks of each node, the nodes in the order of their lowest rank.
    pub ranks_per_node: Vec<usize>,
    /// Per rank, its node in that order.
    pub node: Vec<usize>,
    /// Per rank, the processor name MPI gives (the host).
    pub hosts: Vec<String>,
    /// Per rank, the CPUs it may run on as the kernel reports them ([`cpus_allowed`]),
    /// "–" where they cannot be read.
    pub cpus: Vec<String>,
    /// The MPI library (`MPI_Get_library_version`, its first line) on rank 0.
    pub mpi_library: String,
    /// The Slurm job, if rank 0 runs in one.
    pub slurm: Option<SlurmJob>,
}

impl Placement {
    /// The fewest and the most ranks on a node.
    pub fn ranks_per_node_range(&self) -> (usize, usize) {
        let min = self.ranks_per_node.iter().copied().min().unwrap_or(0);
        let max = self.ranks_per_node.iter().copied().max().unwrap_or(0);
        (min, max)
    }
}

/// The CPUs this process may run on, `Cpus_allowed_list` of `/proc/self/status` (Linux),
/// for example "0-19" or "3"; `None` elsewhere. Rayon's threads inherit it, so it is the
/// binding of the whole rank.
pub fn cpus_allowed() -> Option<String> {
    let status = std::fs::read_to_string("/proc/self/status").ok()?;
    status
        .lines()
        .find_map(|l| l.strip_prefix("Cpus_allowed_list:"))
        .map(|v| v.trim().to_string())
}

/// The [`Placement`] of the ranks of `comm`.
///
/// # Collective operation
///
/// On every rank of `comm`: one `split_shared`, a broadcast on each node, two
/// all-gathers and one all-gather-v.
/// They run after the timed evaluations (requirement 5 of docs/phase5n/README.md:
/// counted here, and in the harness only).
fn placement(comm: &SimpleCommunicator) -> Placement {
    let size = comm.size() as usize;
    // With the rank as key, a node's rank 0 is its lowest rank, which names the node.
    let node = comm.split_shared(comm.rank());
    let mut leader = comm.rank() as u64;
    node.process_at_rank(0).broadcast_into(&mut leader);
    drop(node);
    let mut leader_of = vec![0u64; size];
    comm.all_gather_into(&leader, &mut leader_of[..]);
    let mut leaders = leader_of.clone();
    leaders.sort_unstable();
    leaders.dedup();
    let node_of: Vec<usize> = leader_of
        .iter()
        .map(|l| leaders.binary_search(l).expect("every leader is listed"))
        .collect();
    let mut ranks_per_node = vec![0usize; leaders.len()];
    for &k in &node_of {
        ranks_per_node[k] += 1;
    }
    let host = mpi::environment::processor_name().unwrap_or_else(|_| "unknown".to_string());
    let cpus = cpus_allowed().unwrap_or_else(|| "–".to_string());
    let text = format!("{host}\n{cpus}");
    let gathered = gather_strings(text.as_bytes(), comm);
    let (hosts, cpus) = gathered
        .iter()
        .map(|s| {
            let (h, c) = s.split_once('\n').unwrap_or((s.as_str(), "–"));
            (h.to_string(), c.to_string())
        })
        .unzip();
    let mpi_library = mpi::environment::library_version()
        .ok()
        .and_then(|v| {
            v.trim_matches(char::from(0))
                .lines()
                .next()
                .map(|l| l.trim().to_string())
        })
        .unwrap_or_else(|| "unknown".to_string());
    Placement {
        nodes: leaders.len(),
        ranks_per_node,
        node: node_of,
        hosts,
        cpus,
        mpi_library,
        slurm: SlurmJob::from_env(),
    }
}

/// Every rank's `bytes`, in rank order, as strings (an all-gather of the lengths and an
/// all-gather-v).
fn gather_strings(bytes: &[u8], comm: &SimpleCommunicator) -> Vec<String> {
    let size = comm.size() as usize;
    let length = bytes.len() as i32;
    let mut lengths = vec![0i32; size];
    comm.all_gather_into(&length, &mut lengths[..]);
    let offsets: Vec<i32> = lengths
        .iter()
        .scan(0, |acc, &c| {
            let o = *acc;
            *acc += c;
            Some(o)
        })
        .collect();
    let mut all = vec![0u8; lengths.iter().sum::<i32>() as usize];
    comm.all_gather_varcount_into(
        bytes,
        &mut PartitionMut::new(&mut all[..], &lengths[..], &offsets[..]),
    );
    (0..size)
        .map(|r| {
            let (o, l) = (offsets[r] as usize, lengths[r] as usize);
            String::from_utf8_lossy(&all[o..o + l]).into_owned()
        })
        .collect()
}

/// The positions of the points this rank passes under `input`, ascending.
///
/// # Collective operation
///
/// With [`Input::Owners`], a build of the FMM from the share on every rank of `comm`.
fn input_points<T: Stored + SimdScalar + Equivalence + Default>(
    workload: &Workload,
    input: Input,
    builder: &FmmBuilder<T>,
    comm: &SimpleCommunicator,
) -> Vec<usize> {
    let (rank, size) = (comm.rank() as usize, comm.size() as usize);
    let n = workload.n;
    let share: Vec<usize> = (0..n)
        .filter(|&i| workload.share(i, size) == rank)
        .collect();
    match input {
        Input::Rank0 => (0..n).filter(|_| rank == 0).collect(),
        Input::Share => share,
        Input::Owners => {
            let points: Vec<[f64; 3]> = share.iter().map(|&i| workload.point(i)).collect();
            let fmm: Fmm<'_, T> = builder
                .clone()
                .build(&points, &points, comm)
                .unwrap_or_else(|error| panic!("rank {rank}: the FMM does not build: {error}"));
            let owned = owned_points(&fmm, workload);
            let mut total = 0usize;
            comm.all_reduce_into(&owned.len(), &mut total, SystemOperation::sum());
            assert_eq!(
                total, n,
                "rank {rank}: the owners' input misses or repeats points"
            );
            owned
        }
    }
}

/// The positions of the workload's points that lie in a local leaf of `fmm`, ascending:
/// each point's index on every level of a local leaf, from the domain's box, looked up
/// among the local leaves and confirmed by `geometry::contains`, the octree's own test.
fn owned_points<T: Stored + SimdScalar + Equivalence + Default>(
    fmm: &Fmm<'_, T>,
    workload: &Workload,
) -> Vec<usize> {
    let domain = *fmm.domain();
    let leaves = fmm.plan().index().leaves();
    let mut by_index = HashMap::new();
    let mut levels = BTreeSet::new();
    for j in 0..leaves.nlocal() {
        let (key, level) = (leaves.key(j), leaves.level(j));
        let index = integer_centre(key, level).map(|c| (c - 1) / 2);
        by_index.insert((level, index), key);
        levels.insert(level);
    }
    let bounds = domain.physical_box().coordinates();
    (0..workload.n)
        .filter(|&i| {
            let x = workload.point(i);
            levels.iter().any(|&level| {
                let scale = (1u64 << level) as f64;
                let index: [i64; 3] = core::array::from_fn(|k| {
                    ((x[k] - bounds[k]) / (bounds[k + 3] - bounds[k]) * scale).floor() as i64
                });
                by_index
                    .get(&(level, index))
                    .is_some_and(|&key| contains(key, x, &domain))
            })
        })
        .collect()
}

/// The held boxes of `fmm` on this rank: local, ghost and `Global`.
fn held_boxes<T: Stored + SimdScalar + Equivalence + Default>(fmm: &Fmm<'_, T>) -> [usize; 3] {
    let index = fmm.plan().index();
    let mut held = [0usize; 3];
    for level in 0..index.nlevels() {
        for kind in index.kinds(level) {
            // `KeyType` is nd-octree's, which this crate does not depend on: its
            // `Global` variant is told apart by name.
            let k = if kind.is_ghost() {
                1
            } else if format!("{kind:?}") == "Global" {
                2
            } else {
                0
            };
            held[k] += 1;
        }
    }
    held
}

/// This rank's row before the build times and the resident size.
fn rank_row<T: Stored + SimdScalar + Equivalence + Default>(
    fmm: &Fmm<'_, T>,
    input: usize,
    p: usize,
    ranks: usize,
) -> RankRow {
    let (sources, targets) = fmm.owned_points();
    let traffic = fmm.exchange_traffic();
    let sizes = fmm.exchange_sizes();
    let multipoles = traffic
        .multipoles
        .iter()
        .fold(Traffic::default(), |sum, t| Traffic {
            messages_sent: sum.messages_sent + t.messages_sent,
            messages_received: sum.messages_received + t.messages_received,
            values_sent: sum.values_sent + t.values_sent,
            values_received: sum.values_received + t.values_received,
        });
    let rank_traffic = RankTraffic {
        sources: traffic.sources,
        multipoles,
        coarse_sent: traffic.coarse_sent,
        coarse_received: traffic.coarse_received,
        blocks: [sizes.sent_blocks, sizes.received_blocks],
        charges: [input, sources],
        output: [OUTPUT_VALUES * targets, OUTPUT_VALUES * input],
    };
    let held = held_boxes(fmm);
    let k: usize = held.iter().sum();
    let leaves = fmm.plan().index().leaves();
    let (j_loc, j_all) = (leaves.nlocal(), leaves.len());
    let (mut e_v, mut e_rest) = (0usize, 0usize);
    for lists in fmm.plan().levels() {
        e_v += lists.v().len();
        e_rest += lists.near().len() + lists.w().len() + lists.x().len();
    }
    let s = size_of::<T>() as f64;
    let n_c = ((p + 1) * (p + 1)) as f64;
    let ghost_sources = sizes.ghost_sources;
    let values = rank_traffic.sources.values_sent
        + rank_traffic.sources.values_received
        + multipoles.values_sent
        + multipoles.values_received
        + traffic.coarse_sent
        + traffic.coarse_received;
    let memory = MemoryModel {
        coefficients: 2.0 * n_c * s * k as f64,
        points: (4 * (sources + ghost_sources) + (3 + OUTPUT_VALUES) * targets) as f64 * s,
        index: (32 * k + 13 * j_all) as f64,
        views: (12 * e_v + 4 * e_rest) as f64,
        redistribution: 2.0 * (4 * input + 12 * sources) as f64,
        buffers: values as f64 * s,
        coarse: 16.0 * (sizes.sent_blocks + sizes.received_blocks) as f64,
        partition: 8.0 * ranks as f64,
    };
    RankRow {
        input,
        sources,
        targets,
        leaves: j_loc,
        empty_leaves: fmm.source_counts().iter().filter(|&&c| c == 0).count(),
        lists: fmm.list_sizes(),
        held,
        ghost_sources,
        build: [0.0; 9],
        traffic: rank_traffic,
        memory,
        resident: None,
    }
}

/// The bits of every value of `output`, φ then ∇φ.
fn bits<T: RealScalar>(output: &Output<T>) -> Vec<u64> {
    let mut bits: Vec<u64> = output
        .potential
        .iter()
        .map(|&v| RealScalar::to_f64(v).to_bits())
        .collect();
    if let Some(gradient) = &output.gradient {
        bits.extend(
            gradient
                .as_flattened()
                .iter()
                .map(|&v| RealScalar::to_f64(v).to_bits()),
        );
    }
    bits
}

/// Builds the FMM of `workload` in precision `T` with `settings` on every rank of
/// `comm`, evaluates it and measures it (module documentation).
///
/// # Collective operation
///
/// On every rank of `comm`, with the same arguments; every rank returns the same
/// [`Report`] apart from [`Report::machine`].
///
/// # Panics
///
/// If the FMM does not build or evaluate (for example with `threads` > 1 when MPI
/// provides less than `Threading::Funneled`), or with [`Input::Owners`] if the points
/// found on their owners are not every point once.
pub fn run<T: Stored + SimdScalar + Equivalence + Default>(
    workload: &Workload,
    settings: &Settings,
    comm: &SimpleCommunicator,
) -> Report {
    let (rank, size) = (comm.rank() as usize, comm.size() as usize);
    let builder = FmmBuilder::<T>::new(settings.p)
        .max_level(MAX_LEVEL)
        .max_points_per_leaf(MAX_POINTS_PER_LEAF)
        .gradients(true)
        .threads(settings.threads)
        .strategy(settings.strategy)
        .overlap(settings.overlap == Overlap::On);
    let mine = input_points(workload, settings.input, &builder, comm);
    let points: Vec<[f64; 3]> = mine.iter().map(|&i| workload.point(i)).collect();

    // The builds: the times of each, the last kept.
    let mut fmm: Option<Fmm<'_, T>> = None;
    let mut builds = Vec::new();
    for _ in 0..settings.builds.max(1) {
        drop(fmm.take());
        comm.barrier();
        let start = Instant::now();
        let built = builder
            .clone()
            .build(&points, &points, comm)
            .unwrap_or_else(|error| panic!("rank {rank}: the FMM does not build: {error}"));
        builds.push(build_values(&built.build_timings(), start.elapsed()));
        fmm = Some(built);
    }
    let mut fmm = fmm.expect("at least one build");
    let mut row = rank_row(&fmm, mine.len(), settings.p, size);
    row.build = core::array::from_fn(|k| median(builds.iter().map(|b| b[k]).collect()));

    // The timed evaluations of charge vector 0, the paths alternating.
    let charges: Vec<T> = mine
        .iter()
        .map(|&i| T::from_f64(workload.charge(0, i)))
        .collect();
    let paths = settings.overlap.paths();
    let mut times: Vec<Vec<[f64; 16]>> = vec![Vec::new(); paths.len()];
    let mut differing = 0usize;
    let mut last = None;
    for e in 0..=settings.evaluations {
        let mut outputs = Vec::new();
        for (path, &overlapped) in paths.iter().enumerate() {
            fmm.set_overlap(overlapped);
            comm.barrier();
            let output = fmm
                .evaluate(&charges)
                .unwrap_or_else(|error| panic!("rank {rank}: the FMM does not evaluate: {error}"));
            if e > 0 {
                times[path].push(stage_values(&output.timings, overlapped));
            }
            outputs.push(output);
        }
        if let [blocking, overlapped] = &outputs[..] {
            differing += bits(blocking)
                .iter()
                .zip(bits(overlapped))
                .filter(|(a, b)| **a != *b)
                .count();
        }
        last = outputs.pop();
    }
    let last = last.expect("at least the warm-up");

    // The stage medians and the totals of every evaluation, gathered.
    let mut path_times = Vec::new();
    for (path, &overlapped) in paths.iter().enumerate() {
        let local: [f64; 16] =
            core::array::from_fn(|k| median(times[path].iter().map(|t| t[k]).collect()));
        let mut every = vec![0.0f64; 16 * size];
        comm.all_gather_into(&local[..], &mut every[..]);
        let totals: Vec<f64> = times[path].iter().map(|t| t[15]).collect();
        let mut all_totals = vec![0.0f64; totals.len() * size];
        comm.all_gather_into(&totals[..], &mut all_totals[..]);
        let evaluations = totals.len();
        let wall = median(
            (0..evaluations)
                .map(|e| {
                    (0..size)
                        .map(|r| all_totals[r * evaluations + e])
                        .fold(0.0, f64::max)
                })
                .collect(),
        );
        path_times.push(PathTimes {
            overlapped,
            medians: every.as_chunks::<16>().0.to_vec(),
            wall,
        });
    }
    let differing = (paths.len() == 2).then(|| {
        let mut total = 0usize;
        comm.all_reduce_into(&differing, &mut total, SystemOperation::sum());
        total
    });

    let errors = (settings.vectors > 0)
        .then(|| errors(workload, settings, (&mine, &points), &mut fmm, comm));
    let reference = settings
        .reference
        .then(|| reference(workload, &builder, (&mine, &points), &last, comm));

    // Every rank's row, with the resident size at the end.
    let resident = resident_memory();
    row.resident = resident.map(|(bytes, _)| bytes);
    let local = row.encode();
    let mut every = vec![0.0f64; local.len() * size];
    comm.all_gather_into(&local[..], &mut every[..]);
    let rows = every
        .chunks_exact(local.len())
        .map(RankRow::decode)
        .collect();
    let placement = placement(comm);

    Report {
        machine: if rank == 0 { machine() } else { String::new() },
        workload: *workload,
        settings: *settings,
        precision: if size_of::<T>() == 4 { "f32" } else { "f64" },
        strategy: fmm.strategy(),
        ranks: size,
        threading: fmm.threading().clone(),
        nlevels: fmm.nlevels(),
        rows,
        paths: path_times,
        differing,
        errors,
        reference,
        resident_kind: resident.map_or("not available", |(_, kind)| kind),
        placement,
    }
}

/// The errors of `fmm` against the direct sum (module documentation): `settings.vectors`
/// evaluations and the direct sum over the ranks.
fn errors<T: Stored + SimdScalar + Equivalence + Default>(
    workload: &Workload,
    settings: &Settings,
    (mine, points): (&[usize], &[[f64; 3]]),
    fmm: &mut Fmm<'_, T>,
    comm: &SimpleCommunicator,
) -> Errors {
    let sample = workload.sample(settings.sampled.min(workload.n));
    let targets: Vec<[f64; 3]> = sample.iter().map(|&i| workload.point(i)).collect();
    // The sampled targets this rank passed: their places in the sample and in `mine`.
    let local: Vec<(usize, usize)> = sample
        .iter()
        .enumerate()
        .filter_map(|(s, i)| mine.binary_search(i).ok().map(|r| (s, r)))
        .collect();
    let scale = 4.0 * std::f64::consts::PI;
    let (mut phi_l2, mut phi_max, mut grad_l2, mut grad_max) = (0.0, 0.0, 0.0, 0.0);
    for vector in 0..settings.vectors {
        let charges: Vec<T> = mine
            .iter()
            .map(|&i| T::from_f64(workload.charge(vector, i)))
            .collect();
        let rounded: Vec<f64> = charges.iter().map(|&q| RealScalar::to_f64(q)).collect();
        // The direct sum over this rank's sources, then over every rank.
        let mut phi = vec![0.0; targets.len()];
        let mut grad = vec![[0.0; 3]; targets.len()];
        direct_sum(points, &rounded, &targets, &mut phi, Some(&mut grad));
        let (mut exact_phi, mut exact_grad) = (vec![0.0; phi.len()], vec![0.0; 3 * phi.len()]);
        comm.all_reduce_into(&phi[..], &mut exact_phi[..], SystemOperation::sum());
        comm.all_reduce_into(
            grad.as_flattened(),
            &mut exact_grad[..],
            SystemOperation::sum(),
        );
        let output = fmm
            .evaluate(&charges)
            .unwrap_or_else(|error| panic!("the FMM does not evaluate: {error}"));
        let gradient = output.gradient.as_ref().expect("built with gradients");
        let (mut potential_errors, mut gradient_errors) =
            (ErrorAccumulator::new(), ErrorAccumulator::new());
        for &(s, r) in &local {
            potential_errors.add_values(&output.potential[r..=r], &[exact_phi[s] / scale]);
            let g: [f64; 3] = core::array::from_fn(|c| exact_grad[3 * s + c] / scale);
            gradient_errors.add_vectors(&gradient[r..=r], &[g]);
        }
        let p = reduce(&potential_errors, comm).finish();
        let g = reduce(&gradient_errors, comm).finish();
        phi_l2 += p.l2 * p.l2;
        phi_max += p.max * p.max;
        grad_l2 += g.l2 * g.l2;
        grad_max += g.max * g.max;
    }
    let rms = |sum: f64| (sum / settings.vectors as f64).sqrt();
    Errors {
        vectors: settings.vectors,
        sampled: sample.len(),
        potential: ErrorNorms {
            l2: rms(phi_l2),
            max: rms(phi_max),
        },
        gradient: ErrorNorms {
            l2: rms(grad_l2),
            max: rms(grad_max),
        },
    }
}

/// The accumulator of every rank's `local`: its sums added and its maxima taken over the
/// ranks (two all-reduces).
fn reduce(local: &ErrorAccumulator, comm: &SimpleCommunicator) -> ErrorAccumulator {
    let parts = local.parts();
    let (mut sums, mut maxima) = ([0.0f64; 2], [0.0f64; 2]);
    comm.all_reduce_into(&parts[..2], &mut sums[..], SystemOperation::sum());
    comm.all_reduce_into(&parts[2..], &mut maxima[..], SystemOperation::max());
    ErrorAccumulator::from_parts([sums[0], sums[1], maxima[0], maxima[1]])
}

/// The [`Reference`] check of `output` (charge vector 0): every rank's output gathered on
/// rank 0 with its indices, against the one-rank `Fmm` of `builder` over every point in
/// index order, which rank 0 builds on its own communicator; the result broadcast.
fn reference<T: Stored + SimdScalar + Equivalence + Default>(
    workload: &Workload,
    builder: &FmmBuilder<T>,
    (mine, points): (&[usize], &[[f64; 3]]),
    output: &Output<T>,
    comm: &SimpleCommunicator,
) -> Reference {
    let (rank, size) = (comm.rank() as usize, comm.size() as usize);
    let root = comm.process_at_rank(0);
    let gradient = output.gradient.as_ref().expect("built with gradients");
    let indices: Vec<u64> = mine.iter().map(|&i| i as u64).collect();
    let values: Vec<f64> = (0..mine.len())
        .flat_map(|r| {
            let g = gradient[r].map(RealScalar::to_f64);
            [RealScalar::to_f64(output.potential[r]), g[0], g[1], g[2]]
        })
        .collect();
    let count = mine.len() as i32;
    let mut result = [0.0f64; 4];
    if rank == 0 {
        let mut counts = vec![0i32; size];
        root.gather_into_root(&count, &mut counts[..]);
        let offsets: Vec<i32> = counts
            .iter()
            .scan(0, |acc, &c| {
                let o = *acc;
                *acc += c;
                Some(o)
            })
            .collect();
        let total = counts.iter().sum::<i32>() as usize;
        let mut all_indices = vec![0u64; total];
        root.gather_varcount_into_root(
            &indices[..],
            &mut PartitionMut::new(&mut all_indices[..], &counts[..], &offsets[..]),
        );
        let counts4: Vec<i32> = counts.iter().map(|&c| 4 * c).collect();
        let offsets4: Vec<i32> = offsets.iter().map(|&o| 4 * o).collect();
        let mut all_values = vec![0.0f64; 4 * total];
        root.gather_varcount_into_root(
            &values[..],
            &mut PartitionMut::new(&mut all_values[..], &counts4[..], &offsets4[..]),
        );
        // The one-rank FMM over every point in index order.
        let every: Vec<[f64; 3]> = if mine.len() == workload.n {
            points.to_vec()
        } else {
            (0..workload.n).map(|i| workload.point(i)).collect()
        };
        let charges: Vec<T> = (0..workload.n)
            .map(|i| T::from_f64(workload.charge(0, i)))
            .collect();
        let one = SimpleCommunicator::self_comm();
        let mut fmm: Fmm<'_, T> = builder
            .clone()
            .build(&every, &every, &one)
            .unwrap_or_else(|error| panic!("the one-rank FMM does not build: {error}"));
        let exact = fmm
            .evaluate(&charges)
            .unwrap_or_else(|error| panic!("the one-rank FMM does not evaluate: {error}"));
        let exact_gradient = exact.gradient.as_ref().expect("built with gradients");
        let (mut phi, mut grad) = (ErrorAccumulator::new(), ErrorAccumulator::new());
        let (mut value_max, mut difference_max, mut differing) = (0.0f64, 0.0f64, 0usize);
        for (k, &i) in all_indices.iter().enumerate() {
            let i = i as usize;
            let got = &all_values[4 * k..4 * k + 4];
            let want = [
                RealScalar::to_f64(exact.potential[i]),
                RealScalar::to_f64(exact_gradient[i][0]),
                RealScalar::to_f64(exact_gradient[i][1]),
                RealScalar::to_f64(exact_gradient[i][2]),
            ];
            phi.add_values(&got[..1], &want[..1]);
            grad.add_vectors(&[[got[1], got[2], got[3]]], &[[want[1], want[2], want[3]]]);
            for (a, b) in got.iter().zip(want) {
                value_max = value_max.max(b.abs());
                difference_max = difference_max.max((a - b).abs());
                differing += usize::from(a.to_bits() != b.to_bits());
            }
        }
        assert_eq!(total, workload.n, "every target once");
        result = [
            phi.finish().l2,
            grad.finish().l2,
            difference_max / value_max,
            differing as f64,
        ];
    } else {
        root.gather_into(&count);
        root.gather_varcount_into(&indices[..]);
        root.gather_varcount_into(&values[..]);
    }
    root.broadcast_into(&mut result[..]);
    Reference {
        potential_l2: result[0],
        gradient_l2: result[1],
        max_relative: result[2],
        differing: result[3] as usize,
    }
}

/// Milliseconds with three decimals, or "–" for NaN.
fn ms(seconds: f64) -> String {
    if seconds.is_nan() {
        "–".to_string()
    } else {
        format!("{:.3}", seconds * 1e3)
    }
}

/// Megabytes with one decimal.
fn mb(bytes: f64) -> String {
    format!("{:.1}", bytes / 1e6)
}

/// Above this rank count the per-rank tables are left out (the reduced ones stay).
pub const PER_RANK_ROWS: usize = 128;

impl Report {
    /// The heading of the report: the problem, the ranks and the settings.
    fn heading(&self) -> String {
        format!(
            "{} N = {}, {} p = {}, {} ranks x {} thread(s), input {}",
            self.workload.distribution.name(),
            self.workload.n,
            self.precision,
            self.settings.p,
            self.ranks,
            self.settings.threads,
            self.settings.input.name()
        )
    }

    /// One `key=value` line per path for the sweeps' tables: the problem, the settings,
    /// the wall time, the build, the stage maxima and the compute imbalance, the exchange
    /// times, the errors and the memory.
    pub fn summaries(&self) -> Vec<String> {
        let rows = &self.rows;
        let max = |f: &dyn Fn(&RankRow) -> f64| rows.iter().map(f).fold(0.0, f64::max);
        let build_max: Vec<f64> = (0..BUILD_PARTS.len())
            .map(|k| max(&|r: &RankRow| r.build[k]))
            .collect();
        let resident = rows
            .iter()
            .filter_map(|r| r.resident)
            .fold(f64::NAN, f64::max);
        self.paths
            .iter()
            .map(|path| {
                let compute = path.compute();
                let (exposed, exchanges) = path.exchanges();
                let mut fields = vec![
                    format!("dist={}", self.workload.distribution.name()),
                    format!("n={}", self.workload.n),
                    format!("precision={}", self.precision),
                    format!("p={}", self.settings.p),
                    format!("ranks={}", self.ranks),
                    format!("threads={}", self.settings.threads),
                    format!("input={}", self.settings.input.name()),
                    format!("overlap={}", if path.overlapped { "on" } else { "off" }),
                    format!("strategy={:?}", self.strategy),
                    format!("wall_ms={}", ms(path.wall)),
                    format!("build_ms={}", ms(build_max[8])),
                    format!("redistribution_build_ms={}", ms(build_max[3])),
                ];
                for (k, key) in [
                    (0, "forward"),
                    (5, "upward_local"),
                    (6, "upward_global"),
                    (7, "gather"),
                    (11, "downward"),
                    (12, "leaves"),
                    (14, "backward"),
                    (15, "total"),
                ] {
                    fields.push(format!("{key}_max_ms={}", ms(path.reduced(k)[0])));
                }
                fields.push(format!("compute_max_ms={}", ms(compute[0])));
                fields.push(format!("compute_mean_ms={}", ms(compute[2])));
                fields.push(format!("compute_imbalance={:.3}", compute[0] / compute[2]));
                fields.push(format!("exposed_ms={}", ms(exposed)));
                fields.push(format!("exchanges_ms={}", ms(exchanges)));
                if let Some(e) = &self.errors {
                    fields.push(format!("phi_l2={:.3e}", e.potential.l2));
                    fields.push(format!("grad_l2={:.3e}", e.gradient.l2));
                }
                if let Some(r) = &self.reference {
                    fields.push(format!("reference_phi_l2={:.2e}", r.potential_l2));
                    fields.push(format!("reference_grad_l2={:.2e}", r.gradient_l2));
                }
                if let Some(d) = self.differing {
                    fields.push(format!("overlap_differing={d}"));
                }
                fields.push(format!(
                    "memory_model_max_mb={}",
                    mb(max(&|r: &RankRow| r.memory.total()))
                ));
                fields.push(format!("resident_max_mb={}", mb(resident)));
                let placement = &self.placement;
                fields.push(format!("nodes={}", placement.nodes));
                fields.push(format!(
                    "ranks_per_node={}",
                    placement.ranks_per_node_range().1
                ));
                if let Some(job) = &placement.slurm {
                    fields.push(format!("job={}", job.id));
                }
                format!("summary: {}", fields.join(" "))
            })
            .collect()
    }
}

impl fmt::Display for Report {
    /// The report in Markdown: the heading, the settings, the per-rank tables (up to
    /// [`PER_RANK_ROWS`] ranks), one block of stage times per path, the reduced tables,
    /// the checks, and the [`summaries`](Report::summaries).
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = &self.settings;
        let value_bytes = if self.precision == "f32" { 4 } else { 8 };
        writeln!(f, "## scaling: {}", self.heading())?;
        writeln!(f)?;
        writeln!(f, "- machine: {}", self.machine)?;
        writeln!(
            f,
            "- ranks {}, threads per rank {}; {}",
            self.ranks, s.threads, self.threading
        )?;
        writeln!(
            f,
            "- problem: N = {}, {}; seed {:#x}, every point generated by index; \
             max_level {MAX_LEVEL}, {MAX_POINTS_PER_LEAF} points per leaf; {} levels",
            self.workload.n,
            self.workload.distribution.description(),
            self.workload.seed,
            self.nlevels
        )?;
        writeln!(
            f,
            "- precision {}, p = {}, strategy {:?}, gradients; input: {}; overlap: {}",
            self.precision,
            s.p,
            self.strategy,
            s.input.description(),
            s.overlap.name()
        )?;
        writeln!(
            f,
            "- {} build(s), the median per part; {} timed evaluations per path after one \
             warm-up, charge vector 0, the median per rank and stage, then reduced over the \
             ranks",
            s.builds.max(1),
            s.evaluations
        )?;
        let placement = &self.placement;
        if placement.nodes <= 1 {
            writeln!(
                f,
                "- every time is measured on this machine ({} ranks x {} threads, release \
                 build unless the machine line says otherwise), one node over shared memory; \
                 memory is the formula of distributed-fmm.md §9.2 (*model*) and {}",
                self.ranks, s.threads, self.resident_kind
            )?;
        } else {
            writeln!(
                f,
                "- every time is measured on these {} nodes ({} ranks x {} threads, release \
                 build unless the machine line says otherwise), over the network between the \
                 nodes and shared memory within each; memory is the formula of \
                 distributed-fmm.md §9.2 (*model*) and {}",
                placement.nodes, self.ranks, s.threads, self.resident_kind
            )?;
        }
        let (fewest, most) = placement.ranks_per_node_range();
        let mut hosts: Vec<&str> = Vec::new();
        for (r, host) in placement.hosts.iter().enumerate() {
            if placement.node[r] == hosts.len() {
                hosts.push(host);
            }
        }
        writeln!(
            f,
            "- placement: {} node(s) ({}), ranks per node {}, threads per rank {}; MPI \
             library: {}",
            placement.nodes,
            hosts.join(", "),
            if fewest == most {
                format!("{most}")
            } else {
                format!("{fewest}–{most}")
            },
            s.threads,
            placement.mpi_library
        )?;
        if let Some(job) = &placement.slurm {
            writeln!(f, "- Slurm: {job}")?;
        }
        writeln!(f)?;

        let per_rank = self.ranks <= PER_RANK_ROWS;
        if per_rank {
            writeln!(f, "### Work, held boxes and memory per rank")?;
            writeln!(f)?;
            writeln!(
                f,
                "| rank | input | sources | targets | leaves (empty) | near pairs | V pairs | \
                 W pairs | X pairs | held boxes local / ghost / Global | ghost sources | \
                 memory model, MB (coefficients) | resident, MB |"
            )?;
            writeln!(f, "| --- | {} |", ["---"; 12].join(" | "))?;
            for (r, row) in self.rows.iter().enumerate() {
                writeln!(
                    f,
                    "| {r} | {} | {} | {} | {} ({}) | {} | {} | {} | {} | {} / {} / {} | {} | \
                     {} ({}) | {} |",
                    row.input,
                    row.sources,
                    row.targets,
                    row.leaves,
                    row.empty_leaves,
                    row.lists.u,
                    row.lists.v,
                    row.lists.w,
                    row.lists.x,
                    row.held[0],
                    row.held[1],
                    row.held[2],
                    row.ghost_sources,
                    mb(row.memory.total()),
                    mb(row.memory.coefficients),
                    row.resident.map_or("–".to_string(), mb)
                )?;
            }
            writeln!(f)?;
            writeln!(f, "### Build per rank, ms")?;
            writeln!(f)?;
            writeln!(f, "| rank | {} |", BUILD_PARTS.join(" | "))?;
            writeln!(f, "| --- | {} |", ["---"; 9].join(" | "))?;
            for (r, row) in self.rows.iter().enumerate() {
                let cells: Vec<String> = row.build.iter().map(|&t| ms(t)).collect();
                writeln!(f, "| {r} | {} |", cells.join(" | "))?;
            }
            writeln!(f)?;
            writeln!(f, "### Traffic per rank and evaluation (bytes)")?;
            writeln!(f)?;
            writeln!(
                f,
                "| rank | sources: msgs sent / recv | sources: bytes sent / recv | \
                 multipoles: msgs sent / recv | multipoles: bytes sent / recv | coarse gather: \
                 blocks own / others, bytes own / others | charges forward: bytes sent / recv | \
                 output backward: bytes sent / recv |"
            )?;
            writeln!(f, "| --- | {} |", ["---"; 7].join(" | "))?;
            for (r, row) in self.rows.iter().enumerate() {
                let t = &row.traffic;
                let b = |v: usize| v * value_bytes;
                writeln!(
                    f,
                    "| {r} | {} / {} | {} / {} | {} / {} | {} / {} | {} / {}, {} / {} | {} / {} \
                     | {} / {} |",
                    t.sources.messages_sent,
                    t.sources.messages_received,
                    b(t.sources.values_sent),
                    b(t.sources.values_received),
                    t.multipoles.messages_sent,
                    t.multipoles.messages_received,
                    b(t.multipoles.values_sent),
                    b(t.multipoles.values_received),
                    t.blocks[0],
                    t.blocks[1],
                    b(t.coarse_sent),
                    b(t.coarse_received),
                    b(t.charges[0]),
                    b(t.charges[1]),
                    b(t.output[0]),
                    b(t.output[1])
                )?;
            }
            writeln!(f)?;
            writeln!(f, "### Placement per rank")?;
            writeln!(f)?;
            writeln!(f, "| rank | node | host | CPUs (Cpus_allowed_list) |")?;
            writeln!(f, "| --- | --- | --- | --- |")?;
            for r in 0..self.ranks.min(placement.hosts.len()) {
                writeln!(
                    f,
                    "| {r} | {} | {} | {} |",
                    placement.node[r], placement.hosts[r], placement.cpus[r]
                )?;
            }
            writeln!(f)?;
        } else {
            writeln!(
                f,
                "Per-rank tables left out above {PER_RANK_ROWS} ranks; the reduced tables \
                 follow."
            )?;
            writeln!(f)?;
        }

        // The work, the build, the traffic and the memory reduced over the ranks.
        writeln!(
            f,
            "### Reduced over the ranks: work, build, traffic, memory"
        )?;
        writeln!(f)?;
        writeln!(f, "| quantity | max | min | mean | max / mean |")?;
        writeln!(f, "| --- | --- | --- | --- | --- |")?;
        let rows = &self.rows;
        let line = |f: &mut fmt::Formatter<'_>,
                    name: &str,
                    get: &dyn Fn(&RankRow) -> f64,
                    show: &dyn Fn(f64) -> String|
         -> fmt::Result {
            let [max, min, mean] = reduce_over(rows.iter().map(get));
            let ratio = if mean > 0.0 {
                format!("{:.3}", max / mean)
            } else {
                "–".to_string()
            };
            writeln!(
                f,
                "| {name} | {} | {} | {} | {ratio} |",
                show(max),
                show(min),
                show(mean)
            )
        };
        let count = |v: f64| format!("{v:.0}");
        let bytes = |v: f64| format!("{v:.0}");
        line(f, "sources owned", &|r| r.sources as f64, &count)?;
        line(f, "leaves", &|r| r.leaves as f64, &count)?;
        line(f, "near pairs", &|r| r.lists.u as f64, &count)?;
        line(f, "V pairs", &|r| r.lists.v as f64, &count)?;
        line(f, "W pairs", &|r| r.lists.w as f64, &count)?;
        line(f, "X pairs", &|r| r.lists.x as f64, &count)?;
        line(
            f,
            "held boxes",
            &|r| r.held.iter().sum::<usize>() as f64,
            &count,
        )?;
        line(
            f,
            "held boxes not local (fraction)",
            &|r| (r.held[1] + r.held[2]) as f64 / r.held.iter().sum::<usize>().max(1) as f64,
            &|v| format!("{v:.3}"),
        )?;
        line(f, "ghost sources", &|r| r.ghost_sources as f64, &count)?;
        for (k, part) in BUILD_PARTS.iter().enumerate() {
            line(f, &format!("build: {part}, ms"), &|r| r.build[k], &|v| {
                ms(v)
            })?;
        }
        let vb = value_bytes as f64;
        line(
            f,
            "source exchange: messages sent",
            &|r| r.traffic.sources.messages_sent as f64,
            &count,
        )?;
        line(
            f,
            "source exchange: bytes received",
            &|r| r.traffic.sources.values_received as f64 * vb,
            &bytes,
        )?;
        line(
            f,
            "multipole exchange: messages sent (all levels)",
            &|r| r.traffic.multipoles.messages_sent as f64,
            &count,
        )?;
        line(
            f,
            "multipole exchange: bytes received",
            &|r| r.traffic.multipoles.values_received as f64 * vb,
            &bytes,
        )?;
        line(
            f,
            "coarse gather: bytes received",
            &|r| r.traffic.coarse_received as f64 * vb,
            &bytes,
        )?;
        line(
            f,
            "charges forward: bytes sent",
            &|r| r.traffic.charges[0] as f64 * vb,
            &bytes,
        )?;
        line(
            f,
            "output backward: bytes sent",
            &|r| r.traffic.output[0] as f64 * vb,
            &bytes,
        )?;
        line(f, "memory model, MB", &|r| r.memory.total(), &|v| mb(v))?;
        line(
            f,
            "memory model: coefficients, MB",
            &|r| r.memory.coefficients,
            &|v| mb(v),
        )?;
        line(
            f,
            "memory model: coarse gather buffers and keys, MB",
            &|r| r.traffic.coarse_received as f64 * vb + r.memory.coarse,
            &|v| mb(v),
        )?;
        if rows.iter().all(|r| r.resident.is_some()) {
            line(
                f,
                "resident, MB",
                &|r| r.resident.unwrap_or(f64::NAN),
                &|v| mb(v),
            )?;
        }
        writeln!(f)?;

        for path in &self.paths {
            let name = if path.overlapped {
                "overlapped"
            } else {
                "blocking"
            };
            writeln!(
                f,
                "### Evaluation, {name}: {}, overlap {}",
                self.heading(),
                if path.overlapped { "on" } else { "off" }
            )?;
            writeln!(f)?;
            writeln!(
                f,
                "Evaluation wall time (median over evaluations of the max over ranks of the \
                 total): {} ms",
                ms(path.wall)
            )?;
            writeln!(f)?;
            if per_rank {
                writeln!(f, "| rank | {} |", STAGES.join(" | "))?;
                writeln!(f, "| --- | {} |", ["---"; 16].join(" | "))?;
                for (r, m) in path.medians.iter().enumerate() {
                    let cells: Vec<String> = m.iter().map(|&t| ms(t)).collect();
                    writeln!(f, "| {r} | {} |", cells.join(" | "))?;
                }
                writeln!(f)?;
            }
            writeln!(
                f,
                "| stage, ms (median per rank) | max | min | mean | max / mean |"
            )?;
            writeln!(f, "| --- | --- | --- | --- | --- |")?;
            for (k, stage) in STAGES.iter().enumerate() {
                let [max, min, mean] = path.reduced(k);
                writeln!(
                    f,
                    "| {stage} | {} | {} | {} | {} |",
                    ms(max),
                    ms(min),
                    ms(mean),
                    if mean.is_nan() || mean == 0.0 {
                        "–".to_string()
                    } else {
                        format!("{:.3}", max / mean)
                    }
                )?;
            }
            let [max, min, mean] = path.compute();
            writeln!(
                f,
                "| compute (upward local + downward + leaves) | {} | {} | {} | {:.3} |",
                ms(max),
                ms(min),
                ms(mean),
                max / mean
            )?;
            writeln!(f)?;
            // The slowest rank in compute, and its share of the work.
            let slowest = path
                .medians
                .iter()
                .enumerate()
                .map(|(r, m)| (r, COMPUTE.iter().map(|&k| m[k]).sum::<f64>()))
                .fold((0, f64::NEG_INFINITY), |a, b| if b.1 > a.1 { b } else { a })
                .0;
            let row = &rows[slowest];
            let mean_of = |get: &dyn Fn(&RankRow) -> f64| {
                rows.iter().map(get).sum::<f64>() / rows.len() as f64
            };
            writeln!(
                f,
                "Slowest rank in compute: {slowest}; its work over the mean: sources {:.3}, \
                 leaves {:.3}, near pairs {:.3}, V pairs {:.3}, W pairs {:.3}, X pairs {:.3}",
                row.sources as f64 / mean_of(&|r| r.sources as f64),
                row.leaves as f64 / mean_of(&|r| r.leaves as f64),
                row.lists.u as f64 / mean_of(&|r| r.lists.u as f64),
                row.lists.v as f64 / mean_of(&|r| r.lists.v as f64),
                row.lists.w as f64 / mean_of(&|r| r.lists.w as f64).max(f64::MIN_POSITIVE),
                row.lists.x as f64 / mean_of(&|r| r.lists.x as f64).max(f64::MIN_POSITIVE),
            )?;
            writeln!(f)?;
        }
        if let [blocking, overlapped] = &self.paths[..] {
            let (exposed, _) = overlapped.exchanges();
            let (_, exchanges) = blocking.exchanges();
            writeln!(
                f,
                "C5.2 measure (max over ranks): exposed waits {} ms against blocking \
                 exchanges {} ms = {:.1}%; evaluation {} ms blocking, {} ms overlapped; {} \
                 values of the two paths differ in any bit",
                ms(exposed),
                ms(exchanges),
                100.0 * exposed / exchanges,
                ms(blocking.wall),
                ms(overlapped.wall),
                self.differing.unwrap_or(0)
            )?;
            writeln!(f)?;
        }
        match &self.errors {
            Some(e) => writeln!(
                f,
                "Errors against the direct sum ({} charge vectors, {} sampled targets, root \
                 mean squares): φ L2 {:.3e}, max {:.3e}; ∇φ L2 {:.3e}, max {:.3e}",
                e.vectors,
                e.sampled,
                e.potential.l2,
                e.potential.max,
                e.gradient.l2,
                e.gradient.max
            )?,
            None => writeln!(f, "Errors against the direct sum: not checked in this run")?,
        }
        match &self.reference {
            Some(r) => writeln!(
                f,
                "Against the one-rank FMM over every point in index order (charge vector 0, \
                 every target): relative L2 of φ {:.2e}, of ∇φ {:.2e}; max relative {:.2e}; \
                 {} values differ in any bit",
                r.potential_l2, r.gradient_l2, r.max_relative, r.differing
            )?,
            None => writeln!(f, "Against the one-rank FMM: not checked in this run")?,
        }
        writeln!(f)?;
        for line in self.summaries() {
            writeln!(f, "{line}")?;
        }
        Ok(())
    }
}
