[package]
name = "fmm-plan"
version = "0.1.0-dev"
authors = ["Timo Betcke"]
edition = "2024"
description = "A Fmm scheduler in Rust."
license = "MIT / Apache-2.0"
homepage = "https://codeberg.com.com/nd-project/nd-plan"
repository = "https://codeberg.org/nd-project/nd-plan.git"
readme = "README.md"
keywords = ["numerics"]
categories = ["mathematics", "science"]

[lib]
name = "fmm_plan"

[dependencies]
nd-octree = { path = "../octree" }
rlst = { version = "0.8.0", features = ["mpi"] }
mpi = { version = "0.8.2", features = ["derive", "complex"] }
itertools = "0.15"

[dev-dependencies]
rand_chacha = "0.10"



