name: 🧪 run-examples

on:
  workflow_dispatch:
  schedule:
  - cron: "1 0 * * FRI"

permissions:
  contents: read

jobs:
  run-examples:
    name: run-examples
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: actions/checkout@v6
        with:
          submodules: "true"

      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libclang-dev cmake libfftw3-dev libopenblas-dev openmpi-bin libopenmpi-dev

      - name: Install cargo-templated-examples
        run: cargo install cargo-templated-examples

      - name: Run examples
        run: cargo templated-examples NPROCESSES 3
